version: '3.9'
services:
  app: 
    build: ./front/
    image: benratti/open-pp/front
    ports:
      - 80:80 
      - 443:443
    container_name: front-01
    hostname : front-01.open-pp.dev
    networks:
      - open-pp
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/health"]
      interval: 10s
      timeout: 3s
      retries: 10
      start_period: 5s
  
  api: 
    build: ./api/
    image: benratti/open-pp/api
    container_name: api-01
    hostname: api-01.open-pp.dev
    networks:
      - open-pp
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/health"]
      interval: 10s
      timeout: 3s
      retries: 10
      start_period: 5s

networks:
  open-pp: 
    name: network_open-pp
    driver: bridge
