name: CI Pipeline

on: 
  push: 
    branches:
      - dev
      - main
  pull_request: 
    branches: 
      - dev
      - main

jobs: 
  build-apps:
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v3
      - name: Set up JDK
        uses: actions/setup-java@v3
        with: 
          java-version: '17'
          distribution: 'temurin'
      - name: Build with maven
        working-directory: ./api
        run: mvn --batch-mode install
  
  test-apps: 
    runs-on: ubuntu-latest
    needs: build-apps
    steps: 
      - uses: actions/checkout@v3
      - name: ls
        run: pwd && ls
      - name: Build docker images
        run: docker compose build



